NUMPY

# NumPy Fundamentals

This notebook demonstrates the core NumPy operations used in Data Analytics and Machine Learning.

Topics Covered:
- Array creation
- Reshaping and Flattening
- Array Generating Functions
- Random Number Generation
- Attributes
- Broadcasting
- Deep copy and shallow copy
- Matrix operations
- Stacking array
- Splitting array
- Universal functions
- Indexing and slicing
- Boolean indexing

In [239]:
import numpy as np

Basic Array Creation

In [240]:
##creating an 1d array
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [241]:
##another way to create an array
list=[1,2,3,4,5,6,7]
arr=np.array(list)
print(arr)
print(type(arr))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


A 2D array = array of arrays, so you need nested brackets.

In [242]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [243]:
#another way of representing an 2D array
l=[[1,2,3,4],[5,6,7,8]]
arr=np.array(l)
arr


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Reshaping and Flattening

| Function | Purpose |
|----------|----------|
| `reshape()` | Change dimensions of array |
| `ravel()` | Flatten array (view) |
| `flatten()` | Flatten array (copy) |
| `transpose()` | Swap rows and columns |

If you want to reshape it should have exact length of the array mentioned above

In [244]:
arr=np.array([1,2,3,4,5,6])
##If we are trying to convert 1d it into 2d array or vice-versa we can use an inbuilt function called as reshape
print(arr.reshape(2,3))
##if we check at starting the array is (1,6) which has 6 elements where after reshaping it transforms into (2,3) which have same elements

[[1 2 3]
 [4 5 6]]


In [245]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[0,11,12]])
#we convert from 2D to 1D
print(arr.reshape(1,12))

[[ 1  2  3  4  5  6  7  8  9  0 11 12]]


In [246]:

arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  0, 11, 12])

In [247]:
arr.transpose()

array([[ 1,  4,  7,  0],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

Array Generating Functions

| Function           | Purpose                |
| ------------------ | ---------------------- |
| `zeros()`          | All zeros              |
| `ones()`           | All ones               |
| `full()`           | Constant value         |
| `arange()`         | Range with step        |
| `linspace()`       | Equal divisions        |
| `eye()`            | Identity matrix        |
| `empty()`          | Uninitialized          |


1️⃣ np.zeros() – All zeros
Creates an array filled with 0.

In [248]:
#for 1d
print(np.zeros(2))
#for 2d we use (()) because  it is an array inside another array
print(np.zeros((2,3)))

[0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


2️⃣ np.ones() –Creates an array filled with 1.

In [249]:
#for 1d
print(np.ones(4))
#for 2d
print(np.ones((3,4)))

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


3️⃣ np.full() – Creates an array filled with a specific value

In [250]:
#for 1d
print(np.full((2),7))
#for 2d
print(np.full(((3,4)),7))

[7 7]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


 4️⃣ np.arange() –Creates values from start to stop (excluding stop) with a step size.

np.arange(start, stop, step)


In [251]:
#it start from 0 to given number-1
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [252]:
print(np.arange(1,10,3))

[1 4 7]


5️⃣ np.linspace() – Equal divisions

Divides a range into equal parts (includes both ends).

np.linspace(start, stop, num)

In [253]:
l = np.linspace(1, 10, 5)
print(l)

[ 1.    3.25  5.5   7.75 10.  ]


6️⃣ np.eye() – Identity matrix

Creates a square matrix with:

1 on diagonal

0 elsewhere

In [254]:
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


7️⃣ np.empty() – Uninitialized array

Creates an array without initializing values.

In [255]:
em = np.empty((2, 2))
print(em)


[[1. 1.]
 [1. 1.]]


Random Number Generation


NumPy provides a dedicated random module to generate random numbers for simulations, testing, and machine learning tasks.

| Function | Purpose |
|----------|----------|
| `np.random.rand()` | Random values between 0 and 1 |
| `np.random.randn()` | Random values from standard normal distribution |
| `np.random.randint()` | Random integers within a range |
| `np.random.choice()` | Randomly select values from given array |

1️⃣ np.random.rand()


Generates random float values between 0 and 1.

In [256]:
random_number=np.random.rand(3)
random_number

array([0.37738271, 0.87927014, 0.44015529])

In [257]:
random_number= np.random.rand(2, 3)
print(random_number)


[[0.62941257 0.97198682 0.78740694]
 [0.9225553  0.4058924  0.47475401]]


2️⃣np.random.randn()


Generates random float values between -3 and 3.

In [258]:
random_number=np.random.randn(3)
random_number

array([-1.62960283,  0.54534545, -0.26811289])

In [259]:
random_number=np.random.randn(5,2)
random_number

array([[ 0.36461991,  0.04847691],
       [ 0.94464991,  0.89064371],
       [ 0.33860777,  0.05249178],
       [ 0.59455447, -1.42239983],
       [-1.29054524, -0.75274896]])

3️⃣ np.random.randint() – Random integers

Generates random integers.

np.random.randint(low, high, size)


In [260]:
random_number= np.random.randint(1, 10, 5)
print(random_number)

[2 3 7 5 9]


4️⃣ np.random.choice() – Select value from the array

np.random.randchoice()

-to use above operation the array should be 1D-array


In [261]:
list=[1,2,3,4,5,6]
arr=np.array(list)
random_choice=np.random.choice(arr)
print(random_choice)

3


In [262]:
#now we will try to combine two or more inbuilt functions
final_output=np.arange(10).reshape(5,2)
final_output

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

Attributes

| Attribute | Purpose |
|-----------|----------|
| `shape` | Returns dimensions of array |
| `ndim` | Number of dimensions |
| `size` | Total number of elements |
| `dtype` | Data type of elements |
| `itemsize` | Memory size of one element |

In [263]:
arr=np.array([[1,2,3],
              [4,5,6]])

arr.shape

(2, 3)

In [264]:
arr.size

6

In [265]:
arr.ndim

2

In [266]:
arr.itemsize ##in bytes of the element

8

Numpy Vectorized operations

Arithmetic operations

In [267]:
##ensure that size should same for both
## the operations are done in element wise
arr1=np.array([1,2,3,4,5])
arr2=np.array([4,5,6,7,8])

In [268]:
print("Addition:",arr1+arr2)

Addition: [ 5  7  9 11 13]


In [269]:
print("Subtraction:",arr1-arr2)

Subtraction: [-3 -3 -3 -3 -3]


In [270]:
print("Multiplication:",arr1*arr2)

Multiplication: [ 4 10 18 28 40]


In [271]:
print("Division:",arr1/arr2)

Division: [0.25       0.4        0.5        0.57142857 0.625     ]


In [272]:
print("Floor Division:",arr2//arr1)

Floor Division: [4 2 2 1 1]


In [273]:
print("Power:",arr1**arr2)

Power: [     1     32    729  16384 390625]


Broadcasting

In [274]:
#Broadcasting allows Numpy to perform operations on arrays of different shapes automatically.
l=[1,2,3,4,5,6]
arr=np.array(l)
arr

array([1, 2, 3, 4, 5, 6])

In [275]:
arr+10

array([11, 12, 13, 14, 15, 16])

In [276]:
## we can also do in 2D
arr=np.arange(1,21).reshape(4,5)
arr+20

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

Deep copy-This creates a completely independent array.

Shallow copy-In Numpy, slicing usually creates a view, not a new independent array.


Shallow Copy

In [277]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [278]:
slice=arr[:6]
slice

array([1, 2, 3, 4, 5, 6])

In [279]:
slice=slice*10
slice

array([10, 20, 30, 40, 50, 60])

In [280]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [281]:
##or
arr1=arr.copy()

In [282]:
arr1[0]=100
arr1

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [283]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Deep Copy

In [284]:
arr=np.arange(1,21)
arr1=arr

In [285]:
arr1[0]=12

In [286]:
arr

array([12,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operations

In [287]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [288]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [289]:
#matrix multiplication
a@b

array([[19, 22],
       [43, 50]])

In [290]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [291]:
#transpose
a.T

array([[1, 3],
       [2, 4]])

Stacking Array

In [292]:
##in stack we use only vectors
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [293]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [294]:
np.column_stack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [295]:
np.row_stack((a,b))

C:\Users\prave\AppData\Local\Temp\ipykernel_27180\1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Splitting array

In [296]:
arr=np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [297]:
np.hsplit(arr,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [298]:
np.vsplit(arr,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

Universal Function

 NumPy Universal Functions (ufuncs)

Universal functions (ufuncs) are vectorized functions that operate element-wise on NumPy arrays and support broadcasting.

“NumPy ufuncs are implemented in C and use vectorized operations, reducing Python-level loops and improving cache efficiency.”

1️⃣ Mathematical (Arithmetic) ufuncs

| Function     | Meaning        | Example             |
| ------------ | -------------- | ------------------- |
| `add()`      | Addition       | `np.add(a, b)`      |
| `subtract()` | Subtraction    | `np.subtract(a, b)` |
| `multiply()` | Multiplication | `np.multiply(a, b)` |
| `divide()`   | Division       | `np.divide(a, b)`   |
| `power()`    | Exponent       | `np.power(a, 2)`    |
| `mod()`      | Remainder      | `np.mod(a, 2)`      |


2️⃣ Trigonometric ufuncs

| Function   | Description     |
| ---------- | --------------- |
| `sin()`    | Sine            |
| `cos()`    | Cosine          |
| `tan()`    | Tangent         |
| `arcsin()` | Inverse sine    |
| `arccos()` | Inverse cosine  |
| `arctan()` | Inverse tangent |


3️⃣ Statistical / Aggregation ufuncs

| Function | Purpose            |
| -------- | ------------------ |
| `mean()` | Average            |
| `sum()`  | Total              |
| `min()`  | Minimum            |
| `max()`  | Maximum            |
| `std()`  | Standard deviation |
| `var()`  | Variance           |


4️⃣ Rounding ufuncs

| Function  | Purpose        |
| --------- | -------------- |
| `round()` | Round          |
| `floor()` | Lower integer  |
| `ceil()`  | Higher integer |
| `trunc()` | Truncate       |


5️⃣ Logarithmic and Exponential ufuncs

| Function  | Description |
| --------- | ----------- |
| `log()`   | Natural log |
| `log10()` | Base-10 log |
| `log2()`  | Base-2 log  |
| `exp()`   | eˣ          |


6️⃣ Comparison ufuncs (Return Boolean)

| Function          | Meaning |
| ----------------- | ------- |
| `greater()`       | `>`     |
| `less()`          | `<`     |
| `equal()`         | `==`    |
| `not_equal()`     | `!=`    |
| `greater_equal()` | `>=`    |
| `less_equal()`    | `<=`    |


7️⃣ Logical ufuncs

| Function        | Purpose |
| --------------- | ------- |
| `logical_and()` | AND     |
| `logical_or()`  | OR      |
| `logical_not()` | NOT     |
| `logical_xor()` | XOR     |


8️⃣ Bitwise ufuncs

| Function        | Meaning |
| --------------- | ------- |
| `bitwise_and()` | AND     |
| `bitwise_or()`  | OR      |
| `bitwise_xor()` | XOR     |
| `invert()`      | NOT     |
| `left_shift()`  | <<      |
| `right_shift()` | >>      |



9️⃣ Absolute & Sign ufuncs

| Function | Purpose        |
| -------- | -------------- |
| `abs()`  | Absolute value |
| `fabs()` | Float absolute |
| `sign()` | Sign of number |


🔟 Special ufuncs

| Function    | Purpose          |
| ----------- | ---------------- |
| `maximum()` | Element-wise max |
| `minimum()` | Element-wise min |
| `clip()`    | Limit values     |
| `sqrt()`    | Square root      |


Some examples with arrays

In [299]:
arr=np.array([4,8,12,15])

In [300]:
# square root
print(np.sqrt(arr))

[2.         2.82842712 3.46410162 3.87298335]


In [301]:
#exponential
print(np.exp(arr))

[5.45981500e+01 2.98095799e+03 1.62754791e+05 3.26901737e+06]


In [302]:
#Sine function
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))


[-0.7568025   0.98935825 -0.53657292  0.65028784]
[-0.65364362 -0.14550003  0.84385396 -0.75968791]
[ 1.15782128 -6.79971146 -0.63585993 -0.8559934 ]


In [303]:
print(np.log2(arr))

[2.        3.        3.5849625 3.9068906]


Numpy Slicing and Indexing of Vectors

In [304]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [305]:
##to access the element we use index of the particular element we need
## In array indexing always starts from 0
arr[2]

np.int64(3)

🔹 General Syntax for Slicing-
array[start : stop : step]


start → index to begin (default = 0)

stop → index to end (not included)

step → jump size (default = 1)

In [306]:
arr[1:5]

array([2, 3, 4, 5])

In [307]:
arr[4:]

array([ 5,  6,  7,  8,  9, 10])

In [308]:
arr[:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [309]:
arr[1:10:2]

array([ 2,  4,  6,  8, 10])

In [310]:
## for 2D
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [311]:
#to print element 1 we check which row it is present and which column and we will give the row and column index to print element present at that index
print("Searching index",arr[0][0])

Searching index 1


In [312]:
#we can also do this
print(arr[0,0])

1


Numpy indexing and slicing of matrix

array[row_start:row_stop, col_start:col_stop]

In [313]:
print(arr[2:]) #row_start:row_end

[[ 9 10 11 12]]


In [314]:
print(arr[:2])

[[1 2 3 4]
 [5 6 7 8]]


In [315]:
#to print 7,8,11,12
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [316]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [317]:
#Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [318]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


Boolean Indexing

In [319]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [320]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [321]:
arr[bool_index]

array([12, 14, 16, 18, 20])

In [322]:
#or
arr[arr%2==0]

array([12, 14, 16, 18, 20])

In [323]:
#example of using numpy
#normalization
#to have a mean of 0 and standard deviation
data=np.array([1,2,3,4,5])
mean=np.mean(data)
sd=np.std(data)
normalized_data=(data-mean)/sd
print(f"Normalization:",normalized_data)

Normalization: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [324]:
#mean
mean=np.mean(data)
#median
median=np.median(data)
#mode
standard_deviation=np.std(data)
#variance
variance=np.var(data)
print(f"mean: {mean}")
print(f"median: {median}")
print(f"standard_deviation: {standard_deviation}")
print(f"variance: {variance}")

mean: 3.0
median: 3.0
standard_deviation: 1.4142135623730951
variance: 2.0


and → works on single booleans

& → element-wise logical AND

In [325]:
#example on logical operations
data=np.array([1,2,3,4,5,6,7,8,9,10])
print(f"Values >5 and <9 is {data[(data>5) & (data<9)]}")

Values >5 and <9 is [6 7 8]
