NUMPY

NumPy (short for Numerical Python) is a core Python library for numerical and scientific computing.

It makes working with numbers, arrays, and mathematical operations fast, efficient, and easy.

🔹 Why NumPy is used

Python lists are slow for large numerical data. NumPy provides:

Faster computation (written in C)

Less memory usage

Powerful math functions

🔹 Key Features of NumPy

1️⃣ N-dimensional Arrays (ndarray)

NumPy provides a powerful array object that can store:

1D (vector)

2D (matrix)

nD (tensors)

2️⃣ Faster than Python Lists

3️⃣ Mathematical Operations

4️⃣ Matrix Operations (Very Important for ML & AI)

5️⃣ Used Everywhere

NumPy is the foundation for:

📊 Pandas (data analysis)

🤖 Machine Learning

📈 Data Science

🧠 Deep Learning

📐 Linear Algebra

🎮 Computer Vision

NumPy Array vs Python List

| Feature    | NumPy Array            | Python List             |
| ---------- | ---------------------- | ----------------------- |
| Data type  | Same data type only         | Different types allowed |
| Speed      | Very fast(c-level)          | Slow   er               |
| Operations | Direct math operations | Need loops              |
|Memory efficiency| High         | Low            |


In [2]:
import numpy as np

In [ ]:
##creating an 1d array
arr1=np.array([1,2,3,4,5])
print(arr1)
#to check what type we use type function
print(type(arr1))
#to check shape or dimensions of the array
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2=np.array([1,2,3,4,5,6])
#by doing this we are making it into 2d array by using an inbuilt function as reshape
print(arr2.reshape(1,6)) # one row and 5 elements

[[1 2 3 4 5 6]]


If you want to reshape it should have exact length of the array mentioned above

In [13]:
#another way of representing an 2D array
arr2=np.array([[1,2,3,4,5]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]]
(1, 5)


A 2D array = array of arrays, so you need nested brackets.

In [16]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


| Function           | Purpose                |
| ------------------ | ---------------------- |
| `array()`          | Create array from list |
| `zeros()`          | All zeros              |
| `ones()`           | All ones               |
| `full()`           | Constant value         |
| `arange()`         | Range with step        |
| `linspace()`       | Equal divisions        |
| `eye()`            | Identity matrix        |
| `random.randint()` | Random integers        |
| `rand()`           | Random (0–1)           |
| `empty()`          | Uninitialized          |


1️⃣ np.array() – Create array from list
👉 What it does

Converts a Python list (or list of lists) into a NumPy array.(as mentioned above)

2️⃣ np.zeros() – All zeros
Creates an array filled with 0.

In [ ]:
#for 1d
print(np.zeros(2))
#for 2d because it is an array inside another array
print(np.zeros((2,3)))

[0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


3️⃣ np.ones() –Creates an array filled with 1.

In [ ]:
#for 1d
print(np.ones(4))
#for 2d
print(np.ones((3,4)))

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


4️⃣ np.full() – Creates an array filled with a specific value

In [25]:
#for 1d
print(np.full((2),7))
#for 2d
print(np.full(((3,4)),7))

[7 7]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


5️⃣ np.arange() –Creates values from start to stop (excluding stop) with a step size.

np.arange(start, stop, step)


In [ ]:
#it start from 0 to given number-1
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [31]:
print(np.arange(1,10,3))

[1 4 7]


6️⃣ np.linspace() – Equal divisions

Divides a range into equal parts (includes both ends).

Syntax:
np.linspace(start, stop, num)

In [33]:
l = np.linspace(1, 10, 5)
print(l)


[ 1.    3.25  5.5   7.75 10.  ]


7️⃣ np.eye() – Identity matrix

👉 What it does

Creates a square matrix with:

1 on diagonal

0 elsewhere

In [34]:
e = np.eye(3)
print(e)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


8️⃣ np.random.randint() – Random integers

👉 What it does

Generates random integers.

np.random.randint(low, high, size)


In [35]:
ri = np.random.randint(1, 10, 5)
print(ri)


[8 7 3 6 4]


9️⃣ np.random.rand() – Random (0 to 1)

👉 What it does

Generates random float values between 0 and 1.

In [36]:
rf = np.random.rand(2, 3)
print(rf)


[[0.06983311 0.81387605 0.35856064]
 [0.7002718  0.24561706 0.5966883 ]]


🔟 np.empty() – Uninitialized array

👉 What it does

Creates an array without initializing values.

In [37]:
em = np.empty((2, 2))
print(em)


[[1. 1.]
 [1. 1.]]


In [ ]:
#now we will try to combine two or more inbuilt functions
#we 
np.arange(1,15,3).reshape(5,1)

array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13]])

Attributes

In [ ]:
arr=np.array([[1,2,3],
              [4,5,6]])
print(f"ArraySize {arr.shape}")
print(f"Number of dimensions {arr.ndim}")
print(f'Size(number of elements) {arr.size}')
print(f"datatype of the elements {arr.dtype}")
print(f'Item size {arr.itemsize}') #in bytes of the element

ArraySize (2, 3)
Number of dimensions 2
Size(number of elements )6
datatype of the elements int64
Item size8


Numpy Vectorized operations

In [43]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([4,5,6,7,8])

In [ ]:
#element wise addition
print("Addition:",arr1+arr2)

[ 5  7  9 11 13]


In [45]:
#element wise Subtraction
print("Subtraction:",arr1-arr2)

Subtraction: [-3 -3 -3 -3 -3]


In [46]:
#element wise Multiplication
print("Multiplication:",arr1*arr2)

Multiplication: [ 4 10 18 28 40]


In [50]:
#element wise floor Division
print("Floor Division:",arr2//arr1)

Floor Division: [4 2 2 1 1]


Universal Function

🔥 NumPy Universal Functions (ufuncs)

Universal functions (ufuncs) are vectorized functions that operate element-wise on NumPy arrays and support broadcasting.

“NumPy ufuncs are implemented in C and use vectorized operations, reducing Python-level loops and improving cache efficiency.”

1️⃣ Mathematical (Arithmetic) ufuncs

| Function     | Meaning        | Example             |
| ------------ | -------------- | ------------------- |
| `add()`      | Addition       | `np.add(a, b)`      |
| `subtract()` | Subtraction    | `np.subtract(a, b)` |
| `multiply()` | Multiplication | `np.multiply(a, b)` |
| `divide()`   | Division       | `np.divide(a, b)`   |
| `power()`    | Exponent       | `np.power(a, 2)`    |
| `mod()`      | Remainder      | `np.mod(a, 2)`      |


2️⃣ Trigonometric ufuncs

| Function   | Description     |
| ---------- | --------------- |
| `sin()`    | Sine            |
| `cos()`    | Cosine          |
| `tan()`    | Tangent         |
| `arcsin()` | Inverse sine    |
| `arccos()` | Inverse cosine  |
| `arctan()` | Inverse tangent |


3️⃣ Statistical / Aggregation ufuncs

| Function | Purpose            |
| -------- | ------------------ |
| `mean()` | Average            |
| `sum()`  | Total              |
| `min()`  | Minimum            |
| `max()`  | Maximum            |
| `std()`  | Standard deviation |
| `var()`  | Variance           |


4️⃣ Rounding ufuncs

| Function  | Purpose        |
| --------- | -------------- |
| `round()` | Round          |
| `floor()` | Lower integer  |
| `ceil()`  | Higher integer |
| `trunc()` | Truncate       |


5️⃣ Logarithmic and Exponential ufuncs

| Function  | Description |
| --------- | ----------- |
| `log()`   | Natural log |
| `log10()` | Base-10 log |
| `log2()`  | Base-2 log  |
| `exp()`   | eˣ          |


6️⃣ Comparison ufuncs (Return Boolean)

| Function          | Meaning |
| ----------------- | ------- |
| `greater()`       | `>`     |
| `less()`          | `<`     |
| `equal()`         | `==`    |
| `not_equal()`     | `!=`    |
| `greater_equal()` | `>=`    |
| `less_equal()`    | `<=`    |


7️⃣ Logical ufuncs

| Function        | Purpose |
| --------------- | ------- |
| `logical_and()` | AND     |
| `logical_or()`  | OR      |
| `logical_not()` | NOT     |
| `logical_xor()` | XOR     |


8️⃣ Bitwise ufuncs

| Function        | Meaning |
| --------------- | ------- |
| `bitwise_and()` | AND     |
| `bitwise_or()`  | OR      |
| `bitwise_xor()` | XOR     |
| `invert()`      | NOT     |
| `left_shift()`  | <<      |
| `right_shift()` | >>      |



9️⃣ Absolute & Sign ufuncs

| Function | Purpose        |
| -------- | -------------- |
| `abs()`  | Absolute value |
| `fabs()` | Float absolute |
| `sign()` | Sign of number |


🔟 Special ufuncs

| Function    | Purpose          |
| ----------- | ---------------- |
| `maximum()` | Element-wise max |
| `minimum()` | Element-wise min |
| `clip()`    | Limit values     |
| `sqrt()`    | Square root      |


Some examples with arrays

In [54]:
arr=np.array([4,8,12,15])

In [55]:
# square root
print(np.sqrt(arr))

[2.         2.82842712 3.46410162 3.87298335]


In [56]:
#exponential
print(np.exp(arr))

[5.45981500e+01 2.98095799e+03 1.62754791e+05 3.26901737e+06]


In [ ]:
#Sine function
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))


[-0.7568025   0.98935825 -0.53657292  0.65028784]
[-0.65364362 -0.14550003  0.84385396 -0.75968791]
[ 1.15782128 -6.79971146 -0.63585993 -0.8559934 ]


In [69]:
print(np.log2(arr))

[2.        3.        3.5849625 3.9068906]


Array Slicing and Indexing

In [91]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(f"Array :\n {arr}")

Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In array indexing always starts from 0

In [92]:
#to print element 1 we check which row it is present and which column and we will give the row and column index to print element present at that index
print("Searching index",arr[0][0])

Searching index 1


🔹 General Syntax
array[start : stop : step]


start → index to begin (default = 0)

stop → index to end (not included)

step → jump size (default = 1)

In [97]:
print(arr[2:]) #row_start:row_end

[[ 9 10 11 12]]


In [98]:
print(arr[:2])

[[1 2 3 4]
 [5 6 7 8]]


In [100]:
print(arr[1,2])

7


Syntax for 2D slicing

array[row_start:row_stop, col_start:col_stop]

In [104]:
#to print 7,8,11,12
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [106]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [107]:
#Modify array elements

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [108]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [110]:
#normalization
#to have a mean of 0 and standard deviation

data=np.array([1,2,3,4,5])
mean=np.mean(data)
sd=np.std(data)
normalized_data=(data-mean)/sd
print(f"Normalization:",normalized_data)

Normalization: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [112]:
#mean
mean=np.mean(data)
#median
median=np.median(data)
#mode
standard_deviation=np.std(data)
#variance
variance=np.var(data)
print(f"mean: {mean}")
print(f"median: {median}")
print(f"standard_deviation: {standard_deviation}")
print(f"variance: {variance}")

mean: 3.0
median: 3.0
standard_deviation: 1.4142135623730951
variance: 2.0


🧠 Why & and not and?

and → works on single booleans

& → element-wise logical AND

In [121]:
#some more examples on logical operations
data=np.array([1,2,3,4,5,6,7,8,9,10])
print(f"Values >5 and <9 is {data[(data>5) & (data<9)]}")

Values >5 and <9 is [6 7 8]
